### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by Creotor** [Qowyn/ark-tools#1]
Hi Qowyn,

Thanks for all the effort you put into this. 
I'm having a problem with this working with my server save file. It worked fine with an SP save with two tamed dinos.

Server file size is 225 MB. There's a few mods installed, but none of them modify dinos in any way. Here they are: http://steamcommunity.com/profiles/76561198053278697/myworkshopfiles/?browsefilter=myfavorites

`D:\Downloads\ark-tools>java -jar ark-tools.jar tamed TheIsland.ark dinos
Exception in thread "main" java.lang.NullPointerException
        at qowyn.ark.properties.PropertyReader.readProperty(PropertyReader.java:45)
        at qowyn.ark.structs.StructPropertyList.<init>(StructPropertyList.java:27)
        at qowyn.ark.arrays.ArkArrayStruct.<init>(ArkArrayStruct.java:26)
        at qowyn.ark.arrays.ArkArrayReader.read(ArkArrayReader.java:32)
        at qowyn.ark.properties.PropertyArray.<init>(PropertyArray.java:23)
        at qowyn.ark.properties.PropertyReader.readProperty(PropertyReader.java:59)
        at qowyn.ark.GameObject.loadProperties(GameObject.java:335)
        at qowyn.ark.ArkSavegame.readBinaryObjectProperties(ArkSavegame.java:222)
        at qowyn.ark.ArkSavegame.readBinary(ArkSavegame.java:129)
        at qowyn.ark.ArkSavegame.<init>(ArkSavegame.java:60)
        at qowyn.ark.ArkSavegame.<init>(ArkSavegame.java:46)
        at qowyn.ark.tools.AnimalListCommands.tamed(AnimalListCommands.java:78)
        at qowyn.ark.tools.App.main(App.java:30)`

Also posted this in the survivetheark.com thread

**Comment by tamaster92** [comment]
Same error but file size is only 48mb, also have mods installed on server though

**Comment by Qowyn** [comment]
Uploaded ark-tools-issue-1.zip which might make your savegames processable. Would really like to take a look at one of those savegames.

Also a savegame with 225MB and the new format seems huge. I'd like to do some performance testing with that because i had disabled some code that potentially increases performance for large saves.

**Comment by Creotor** [comment]
The server (PvE) has been around since July (or late June) 2015; I clean it weekly, but yea... Heard from one server owner that no matter what he did, saves would eventually become bloated and only wipes could fix that, /shrug. Maybe there's piles of useless data in it.

Gladly sharing the save: 
https://mega.nz/#!cE9ECZJQ!kp7FkDmh7gVYiwwpnxSt1wl5Png3YTGJx0BdRobYbIA

The new upload worked much better! Got some warnings below, but it pulled a large number of dinos from the file.

`D:\Downloads\ark-tools\ark-tools-issue-1>java -jar ark-tools.jar tamed TheIsland.ark dinos
Found invalid nametable index -11064320 at 3379d36
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -8519474 at 337a05c
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -8519474 at 35a7e73
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -14463232 at 3f05ed0
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -14463232 at 41a8bba
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 41a8ed0
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -16711936 at 43d038d
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -14463232 at 43d06b8
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 43d09de
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 43d0f50
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -11064320 at 43d127b
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -11064320 at 43f30b4
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 43fcf8d
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -14463232 at 43fd5f0
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -14463232 at 43fda0d
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -11064320 at 43feeac
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -11064320 at 43ff1c3
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -11064320 at 43ff4da
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -11064320 at 43ff7f1
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -11064320 at 43ffb08
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 43ffe1e
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 4400134
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 440044a
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 4400760
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -14463232 at 4400a75
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -14463232 at 4400d8a
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 44010a0
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 44013b6
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -11064320 at 4598ef2
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 4599208
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -14463232 at 4599646
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -14463232 at 459995b
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 4599c71
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 4599f87
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 459a297
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -11064320 at 459a7f4
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 459b0d7
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -14463232 at 459b3ec
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -11064320 at 501fdae
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -11064320 at 5193ab5
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -1 at 51cbb5d
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -3031808 at 51cbf4f
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -6251 at 51cc3fc
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -16711681 at 6046d0e
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -16776961 at 60472b5
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -16776961 at 713844a
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -11064320 at 96667ac
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -11064320 at b8b3c72
Warning: Property name is null. Ignoring remaining properties.
Found invalid nametable index -11064320 at bef0afd
Warning: Property name is null. Ignoring remaining properties.
Reading finshed after 5840 ms
Dump finshed after 343 ms
Completly finshed after 6183 ms`

Btw, would you think about adding a total of tamed dinos per class or overall? And if that is even possible, date of tame (in-game or actual time)?

**Comment by Qowyn** [comment]
New version released, improved loading times for me by about... 700%
Also no more warnings and basic statics, including the count of each dino class. Date of tame needs more research, in-game time might be impossible because the length of night and day can be changed.
I'll now try to find some editor capable of loading the 1,3 GB json version of that save 😄

**Comment by Creotor** [comment]
Haha, have fun and thanks!
