### ISSUE TITLE
Coordinates extracted from Ragnarok save game not accurate

### ISSUE THREAD

**Issue by TheRealestMVP** [Qowyn/ark-tools#11]
I'm using ark-tools to extract tamed dino coordinates from various save games. It works well on The Island, The Center and Scorched Earth.

But on my Ragnarok save games (using the official DLC), the exported lat/lon coordinates are weird. None of the coordinates match the dino positions, and many coordinates even have negative values.

Is there anything I could be doing wrong? Is Ragnarok special or is it maybe needed to build in support for new maps in ark-tools?

**Comment by Qowyn** [comment]
Every map that doesn't use the same size as TheIsland needs special support added. Going to release a new version in a few minutes with support for TheVolcano and Ragnarok.

**Comment by TheRealestMVP** [comment]
That's great. Huge kudos for you!
