### ISSUE TITLE
How is ark_data.json exported from the game?

### ISSUE THREAD

**Issue by cokll** [Qowyn/ark-tools#14]
Can export the data for mod?
Thx.

**Comment by Qowyn** [comment]
The data is coming from another tool i created, from the cooked data of the game itself. The problem with including mod data is: there are way too many mods. The whole process is located on a dedicated server, but that server is lacking performance and space. Source is currently unavailable, but i'm working on a solution, which will required github authentication via github, as the tool is partly based on Unreal Engine code.

**Comment by cokll** [comment]
ok thank
