### ISSUE TITLE
Error with large filesize

### ISSUE THREAD

**Issue by tamaster92** [Qowyn/ark-tools#2]
[http://puu.sh/qq4iC/994bb2f760.png](url)
Image of error

[https://dl.dropboxusercontent.com/u/23158716/TheIsland.ark](url)
link to savefile

Seems to be a memory issue :) Hope you can fix it!

**Comment by Qowyn** [comment]
If you managed to get that with version 0.0.4 you probably deserve a prize. Going to take a look tomorrow.

**Comment by tamaster92** [comment]
0.0.4 indeed :) save game is about 350mb

**Comment by tamaster92** [comment]
Should point out that trying it with our test server save (the center and 52mb) it works perfect

**Comment by Qowyn** [comment]
Ignoring the strange property names used by some mod (Example: CustomColours_60_7D3267C846B277953C0C41AEBD54FBCB), this save is just huge. Over 1,000,000 Objects :D Memory requirements can currently be somewhat high, will fix this later by reading files in a streaming way.

In the meantime launching with java -jar ark-tools.jar -Xmx 2G should fix the error, causing java to consume up to 2GB RAM while the program is running. Which might be a problem, considering java 8 uses either 1GB RAM or 1/4 of your total RAM by default.

**Comment by tamaster92** [comment]
Will test that ASAP tomorrow thank you :)

**Comment by tamaster92** [comment]
I presume I am just using it wrong but -

http://puu.sh/qrInf/ea900269f7.png

Doesn't work

**Comment by Qowyn** [comment]
I just failed multiple times. Correct command:
java -Xmx2G -jar ark-tools.jar
So i posted wrong order of options and there can be no space between -Xmx and 2G

**Comment by tamaster92** [comment]
hmmm

http://puu.sh/qrMGt/30ad5b9251.png

telling me not enough space but i have 16gb RAM, and tons of HDD space left :/

**Comment by tamaster92** [comment]
installed 64bit java and boom, worked.

Thank you!
