### ISSUE TITLE
New issue dumping player data

### ISSUE THREAD

**Issue by Letoric** [Qowyn/ark-tools#26]
![image](https://user-images.githubusercontent.com/26984630/30571629-ab6e217c-9cae-11e7-803d-d4186aa0d45d.png)

Let me know if you need data files, but it's consistent across 5 servers. This occurs when using the --positions option.

**Comment by Qowyn** [comment]
And that is the exact reason why i shouldn't release stuff if I'm tired.

**Comment by Qowyn** [comment]
Fixed with 0.6.4
