### ISSUE TITLE
Error when trying to use TheVolcano.ark

### ISSUE THREAD

**Issue by tamaster92** [Qowyn/ark-tools#4]
http://puu.sh/s1ZJx/e4920cec12.png

**Comment by Qowyn** [comment]
I'd really like to take a look at that savegame. Looks like that savegame contains something that i haven't seen/analyzed before.

**Comment by tamaster92** [comment]
http://puu.sh/s7h3N/88cd74bc0d.ark

**Comment by Qowyn** [comment]
Sorry about the increased response time, will take a look ASAP

**Comment by Qowyn** [comment]
Should be resolved with 0.4.0

**Comment by Qowyn** [comment]
I need that savegame as well, this could finally reveal the structure of those fields. TheVolcano didn't have enough data, so i had to apply a band-aid.

**Comment by TyrelSackett** [comment]
Hey Qowyn, I'll send you a fresh map file today with all that data.. I have to prep a new island map for the new patch coming so i'll load the SGA mod again and place a couple of gates and then send you the save file here!

Sorry for the delayed response. work/life/holidays.. fun!

Thanks

**Comment by Qowyn** [comment]
Finally fixed with the new version
