### ISSUE TITLE
Update doesn't seem to work

### ISSUE THREAD

**Issue by Letoric** [Qowyn/ark-tools#9]
![image](https://cloud.githubusercontent.com/assets/26984630/26796917/d1545c6e-49f0-11e7-93e0-594928cb98a6.png)
This is with a fresh download a few minutes ago.

**Comment by Letoric** [comment]
Here's using the extended command as I interpreted it.
![image](https://cloud.githubusercontent.com/assets/26984630/26796978/016b2bb2-49f1-11e7-8fa3-52ce2b7778a9.png)

**Comment by Qowyn** [comment]
Should be just `.\ark-tools.exe updateData` without the duplicate Update in there.
I'm planning to add an update command once the jar is signed.

**Comment by Letoric** [comment]
Doh. My bad :)
